version: '3.7'

services:
  server:
    build: ./server
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
  frontend:
    build: ./front
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
